### ISSUE TITLE
New redis plugin release

### ISSUE THREAD

**Issue by tamershahin** [burtbeckwith/grails-standalone-tomcat-redis#2]
the redis grails plugin has been released: is a 1.4.1 now. it uses new version of jedis, the 2.2.0.
Are there any plan to move this plugin to new jedis version?

**Comment by dtanner** [comment]
0.2 is out now with that change, and I just did a quick successful test of using the latest redis plugin.  So this can probably be closed.

**Comment by dtanner** [comment]
I just submitted a pull request to update the tomcat-redis-session library to jedis 2.2.  https://github.com/zinin/tomcat-redis-session/pull/4
When that's fixed, that should fix this issue...sorry for the incomplete info earlier.
