### ISSUE TITLE
library problems

### ISSUE THREAD

**Issue by tamershahin** [burtbeckwith/grails-standalone-tomcat-redis#5]
Hi!
I submitted a new pull request because Alexander Zinin release a new version of the tomcat session library (0.6).

The problem is that i tryed to fork the grails-standalone-tomcat-redis and changed it locally to use the new library version. 
But it only compile and work smoothly using it as inline plugin. when I try to run package-plugin and install it in local maven cache i got this error:

StandaloneTomcatRedisGrailsPlugin.groovy: 3: unable to resolve class ru.zinin.redis.session.RedisManager
 @ line 3, column 1.
   import ru.zinin.redis.session.RedisManager

I know that inline plugin follow different compilation steps than the regular one, but i keep guessing where is the problem.

Since you don't have this problem when you package the plugin and commit it to grails.org, can it be some problem in my local configuration?

thanks for the support, I heavily rely on this and redis plugin for my project so I need to have them up to date with last bugfix.

Tamer

**Comment by burtbeckwith** [comment]
I released version 0.3 with your PR applied.

**Comment by tamershahin** [comment]
Thanks! now everything works smoothly! :)
I just made a lot of tests and released the 0.2 version on my redis cache plugin.
